force-app/main/default/objects/Case/fields/FS_AceptaRespuesta__c.field-meta.xml
<CustomField>
    <fullName>FS_AceptaRespuesta__c</fullName>
    <label>Acepta Respuesta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ValoresSiNo</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/FS_CorreosNotificacionesServicios__c.field-meta.xml
<CustomField>
    <fullName>FS_CorreosNotificacionesServicios__c</fullName>
    <label>Correos Notificaciones Servicios</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField> 

force-app/main/default/objects/Case/fields/FS_SubEstado__c.field-meta.xml
<CustomField>
    <fullName>FS_SubEstado__c</fullName>
    <label>Sub Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Apertura de caso</fullName>
                <default>true</default>
                <label>Apertura de caso</label>
            </value>
            <value>
                <fullName>Entrega 1a respuesta</fullName>
            </value>
            <value>
                <fullName>Información validada</fullName>
            </value>
            <value>
                <fullName>Análisis N1</fullName>
            </value>
            <value>
                <fullName>Desarrollo Incidente Definitivo</fullName>
            </value>
            <value>
                <fullName>Revisión Documentación N2</fullName>
            </value>
            <value>
                <fullName>Desarrollo Incidente Puntual</fullName>
            </value>
            <value>
                <fullName>Aprobación Solución IP-N2</fullName>
            </value>
            <value>
                <fullName>Aprobación de Solución IP-Release</fullName>
            </value>
            <value>
                <fullName>Costo Aceptado</fullName>
            </value>
            <value>
                <fullName>Costo Rechazado</fullName>
            </value>
            <value>
                <fullName>Análisis Falla Operativa</fullName>
            </value>
            <value>
                <fullName>Escalado a N2</fullName>
            </value>
            <value>
                <fullName>Análisis N2</fullName>
            </value>
            <value>
                <fullName>Envío de respuesta</fullName>
            </value>
            <value>
                <fullName>Respuesta aceptada</fullName>
            </value>
            <value>
                <fullName>Respuesta rechazada</fullName>
            </value>
            <value>
                <fullName>En reproceso por rechazo</fullName>
            </value>
            <value>
                <fullName>En Espera de Respuesta del Cliente</fullName>
            </value>
            <value>
                <fullName>Elaboración Diseño Técnico</fullName>
            </value>
            <value>
                <fullName>Aprobación Diseño Técnico</fullName>
            </value>
            <value>
                <fullName>Validación-Entrega de Fuentes</fullName>
            </value>
            <value>
                <fullName>Elaboración Solución Definitiva</fullName>
            </value>
            <value>
                <fullName>Aprobación Solución Definitiva N2</fullName>
            </value>
            <value>
                <fullName>Aprobación Solución Definitiva Releases</fullName>
            </value>
            <value>
                <fullName>Escalado a QA</fullName>
            </value>
            <value>
                <fullName>Elaboración Plan de Pruebas</fullName>
            </value>
            <value>
                <fullName>Aprobación Plan de Pruebas</fullName>
            </value>
            <value>
                <fullName>Instalación Parche Releases</fullName>
            </value>
            <value>
                <fullName>Aprobación Instalación Parche - Releases</fullName>
            </value>
            <value>
                <fullName>Paso a Producción</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/JobValidacionRespuesta.cls
global without sharing class JobValidacionRespuesta implements Schedulable { 
    
    global void execute(SchedulableContext ctx) {
        recordatorioRespuesta();
        recordatorioEncuesta();
        recordatorioPaseProdccion();
    }
    
    public static void recordatorioRespuesta(){
        DateTime fecha = DateTime.now().addDays(-Integer.valueOf(Label.FS_DiasEnvioEncuesta));
        String nombrePlantilla = 'FS_ValidacionInformacion';
        String subEstado = 'Envío de respuesta';
        List<Messaging.SingleEmailMessage> MessageList = new List<Messaging.SingleEmailMessage>();
        EmailTemplate plantilla = [Select Id, Subject, HTMLValue from EmailTemplate Where DeveloperName = :nombrePlantilla limit 1];
        OrgWideEmailAddress[] owea = [select Id from OrgWideEmailAddress where Address = :Label.FS_CorreoElectronicoServicio];
        String query = camposCaso();
        List<Case> listCasos = new List<Case>();
        query += ' Where FS_SubEstado__c = :subEstado and IsClosed = false';
        for(Case item: Database.query(query)){
            try{
                if(item.FS_AceptaRespuesta__c == null && item.LastModifiedDate >= fecha){
                    Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                    String asunnto = CaseTriggerHelper.reemplazarCampos(item, plantilla.Subject, 'Case');
                    String html = CaseTriggerHelper.reemplazarCampos(item, plantilla.HTMLValue, 'Case');
                    String urlLogo = CaseTriggerHelper.getLogoImagen();
                    html = CaseTriggerHelper.getLogoImagen() + html.replace('{urlSiteServicios}', Label.FS_UrlPortalServicios);
                    html =html.replace('{urlSiteEncuestas}', Label.FS_UrlPortalEncuestas);
                    html = html.replace(']]>', '') + '</td><td style="width: 25%;" /></table></body></html>';
                    html = html.replace('<![CDATA[', '');
                    mail.setSubject(asunnto);
                    mail.setHtmlBody(html);
                    mail.saveAsActivity = true;
                    mail.setWhatId(item.Id);
                    mail.setTargetObjectId(item.ContactId);
                    mail.setOrgWideEmailAddressId(owea.get(0).Id);
                    if(String.isNotBlank(item.FS_CorreosNotificacionesServicios__c)){
                        mail.setCcAddresses(item.FS_CorreosNotificacionesServicios__c.split(','));
                    }
                    MessageList.add(mail);
                }else{
                    listCasos.add(new Case (Id = item.Id, Status = 'Cerrado'));
                }
            }catch(exception ex){
                System.debug('Error: '+ex.getMessage() + ' Línea: ' + ex.getLineNumber());
            }
        }
        Messaging.SendEmailResult[] results = Messaging.sendEmail(MessageList);
        DataBase.update(listCasos, false);
    }
    
    public static void recordatorioEncuesta(){
        DateTime fecha = DateTime.now().addDays(-Integer.valueOf(Label.FS_DiasEnvioEncuesta));
        String nombrePlantilla = 'FS_Encuesta';
        String subEstado = 'Respuesta aceptada';
        List<Messaging.SingleEmailMessage> MessageList = new List<Messaging.SingleEmailMessage>();
        EmailTemplate plantilla = [Select Id, Subject, HTMLValue from EmailTemplate Where DeveloperName = :nombrePlantilla limit 1];
        OrgWideEmailAddress[] owea = [select Id from OrgWideEmailAddress where Address = :Label.FS_CorreoElectronicoServicio];
        String query = camposCaso();
        List<Case> listCasos = new List<Case>();
        query += ' Where FS_SubEstado__c = :subEstado and IsClosed = false';
        for(Case item: Database.query(query)){
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            try{
                if(item.FS_FechaEnvioEncuesta__c >= fecha){
                    
                    String asunnto = CaseTriggerHelper.reemplazarCampos(item, plantilla.Subject, 'Case');
                    String html = CaseTriggerHelper.reemplazarCampos(item, plantilla.HTMLValue, 'Case');
                    String urlLogo = CaseTriggerHelper.getLogoImagen();
                    html = CaseTriggerHelper.getLogoImagen() + html.replace('{urlSiteServicios}', Label.FS_UrlPortalServicios);
                    html =html.replace('{urlSiteEncuestas}', Label.FS_UrlPortalEncuestas);
                    html = html.replace(']]>', '') + '</td><td style="width: 25%;" /></table></body></html>';
                    html = html.replace('<![CDATA[', '');
                    mail.setSubject(asunnto);
                    mail.setHtmlBody(html);
                    mail.saveAsActivity = true;
                    mail.setWhatId(item.Id);
                    mail.setTargetObjectId(item.ContactId);
                    mail.setOrgWideEmailAddressId(owea.get(0).Id);
                    if(String.isNotBlank(item.FS_CorreosNotificacionesServicios__c)){
                        mail.setCcAddresses(item.FS_CorreosNotificacionesServicios__c.split(','));
                    }
                    MessageList.add(mail);
                    
                }else{
                    listCasos.add(new Case (Id = item.Id, Status = 'Cerrado'));
                }
            }catch(exception ex){
                System.debug('Error: '+ex.getMessage() + ' Línea: ' + ex.getLineNumber());
            }
        }
        Messaging.SendEmailResult[] results = Messaging.sendEmail(MessageList);
        DataBase.update(listCasos, false);
    }
    
      public static void recordatorioPaseProdccion(){
        DateTime fecha = DateTime.now().addDays(-Integer.valueOf(Label.FS_DiasEnvioEncuesta));
        String nombrePlantilla = 'FS_PaseProduccion';
        String subEstado = 'Paso a Producción';
        List<Messaging.SingleEmailMessage> MessageList = new List<Messaging.SingleEmailMessage>();
        EmailTemplate plantilla = [Select Id, Subject, HTMLValue from EmailTemplate Where DeveloperName = :nombrePlantilla limit 1];
        OrgWideEmailAddress[] owea = [select Id from OrgWideEmailAddress where Address = :Label.FS_CorreoElectronicoServicio];
        String query = camposCaso();
        List<Case> listCasos = new List<Case>();
        query += ' Where FS_SubEstado__c = :subEstado and IsClosed = false';
        for(Case item: Database.query(query)){
            try{
                if(item.LastModifiedDate >= fecha){
                    Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                    String asunnto = CaseTriggerHelper.reemplazarCampos(item, plantilla.Subject, 'Case');
                    String html = CaseTriggerHelper.reemplazarCampos(item, plantilla.HTMLValue, 'Case');
                    String urlLogo = CaseTriggerHelper.getLogoImagen();
                    html = CaseTriggerHelper.getLogoImagen() + html.replace('{urlSiteServicios}', Label.FS_UrlPortalServicios);
                    html =html.replace('{urlSiteEncuestas}', Label.FS_UrlPortalEncuestas);
                    html = html.replace(']]>', '') + '</td><td style="width: 25%;" /></table></body></html>';
                    html = html.replace('<![CDATA[', '');
                    mail.setSubject(asunnto);
                    mail.setHtmlBody(html);
                    mail.saveAsActivity = true;
                    mail.setWhatId(item.Id);
                    mail.setTargetObjectId(item.ContactId);
                    mail.setOrgWideEmailAddressId(owea.get(0).Id);
                    if(String.isNotBlank(item.FS_CorreosNotificacionesServicios__c)){
                        mail.setCcAddresses(item.FS_CorreosNotificacionesServicios__c.split(','));
                    }
                    MessageList.add(mail);
                }else{
                    listCasos.add(new Case (Id = item.Id, Status = 'Cerrado'));
                }
            }catch(exception ex){
                System.debug('Error: '+ex.getMessage() + ' Línea: ' + ex.getLineNumber());
            }
        }
        Messaging.SendEmailResult[] results = Messaging.sendEmail(MessageList);
        DataBase.update(listCasos, false);
    }
  
    
    public static String camposCaso(){
        Map<String, Schema.SObjectField> fieldMap = Schema.getGlobalDescribe().get('Case').getDescribe().fields.getMap();
        String query = 'Select ';
        for(Schema.SObjectField sfield : fieldMap.Values()){
            schema.describefieldresult dfield = sfield.getDescribe();
            query += dfield.getname() + ',';
        }
        query =  query.substring(0, query.length() - 1) + ' From Case ';
        return query;
    }
    
}