force-app/main/default/objects/Case/fields/FS_Modulo__c.field-meta.xml
<CustomField>
    <fullName>FS_Modulo__c</fullName>
    <label>Módulo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GENERALES</fullName>
            </value>
            <value>
                <fullName>CLIENTES</fullName>
            </value>
            <value>
                <fullName>CAJA Y SERVICIOS</fullName>
            </value>
            <value>
                <fullName>CAPTACIONES VISTA</fullName>
            </value>
            <value>
                <fullName>CAPTACIONES A PLAZO</fullName>
            </value>
            <value>
                <fullName>COLOCACIONES</fullName>
            </value>
            <value>
                <fullName>ESTABLECIMIENTOS</fullName>
            </value>
            <value>
                <fullName>TARJETA DE CREDITO</fullName>
            </value>
            <value>
                <fullName>COMERCIO EXTERIOR</fullName>
            </value>
            <value>
                <fullName>MESA DE DINERO</fullName>
            </value>
            <value>
                <fullName>SERVICIOS</fullName>
            </value>
            <value>
                <fullName>TARJETA DE DEBITO</fullName>
            </value>
            <value>
                <fullName>INF. MANAGEMEN SYST. (IMS)</fullName>
            </value>
            <value>
                <fullName>CHECK CLEARING (ECCO)</fullName>
            </value>
            <value>
                <fullName>PROCESO DE DOCUMENTO (DIPS)</fullName>
            </value>
            <value>
                <fullName>CONTABILIDAD</fullName>
            </value>
            <value>
                <fullName>REPORTES DEL SISTEMA</fullName>
            </value>
            <value>
                <fullName>GARANTIAS</fullName>
            </value>
            <value>
                <fullName>SEGURIDAD INTERNA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/FS_Producto__c.field-meta.xml
<CustomField>
    <fullName>FS_Producto__c</fullName>
    <label>Producto</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FISA System</fullName>
            </value>
            <value>
                <fullName>FISA - Business Platform</fullName>
            </value>
            <value>
                <fullName>FISA Credit Card</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/FS_SubModulo__c.field-meta.xml
<CustomField>
    <fullName>FS_SubModulo__c</fullName>
    <label>Sub Módulo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Parametrización</fullName>
            </value>
            <value>
                <fullName>ACH</fullName>
            </value>
            <value>
                <fullName>Ajustes</fullName>
            </value>
            <value>
                <fullName>Apertura caja</fullName>
            </value>
            <value>
                <fullName>Auxiliares</fullName>
            </value>
            <value>
                <fullName>Bloqueos</fullName>
            </value>
            <value>
                <fullName>Bloqueos/Desbloqueos</fullName>
            </value>
            <value>
                <fullName>Cancelación</fullName>
            </value>
            <value>
                <fullName>Carga de Información</fullName>
            </value>
            <value>
                <fullName>Cargos/Comisiones/Impuestos</fullName>
            </value>
            <value>
                <fullName>Cartas de Crédito</fullName>
            </value>
            <value>
                <fullName>Cierre</fullName>
            </value>
            <value>
                <fullName>Clientes</fullName>
            </value>
            <value>
                <fullName>Cobranzas</fullName>
            </value>
            <value>
                <fullName>Comprobantes Fiscales</fullName>
            </value>
            <value>
                <fullName>Compromisos/Líneas de Crédito</fullName>
            </value>
            <value>
                <fullName>Consulta</fullName>
            </value>
            <value>
                <fullName>Contabilidad</fullName>
            </value>
            <value>
                <fullName>Convenios</fullName>
            </value>
            <value>
                <fullName>Cuadre</fullName>
            </value>
            <value>
                <fullName>Cupones</fullName>
            </value>
            <value>
                <fullName>Desembolso</fullName>
            </value>
            <value>
                <fullName>Estados de Cuenta</fullName>
            </value>
            <value>
                <fullName>Facturación</fullName>
            </value>
            <value>
                <fullName>Facturas</fullName>
            </value>
            <value>
                <fullName>Garantias</fullName>
            </value>
            <value>
                <fullName>Generación de Comprobantes</fullName>
            </value>
            <value>
                <fullName>Incrementos</fullName>
            </value>
            <value>
                <fullName>Inicio/Fin de día</fullName>
            </value>
            <value>
                <fullName>Integración</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_ProductoAdquirido__c/FS_ProductoAdquirido__c.object-meta.xml
<CustomObject>
    <label>Producto Adquirido</label>
    <nameField>
        <label>Nombre de Categoría</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Productos Adquiridos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_ProductoAdquirido__c/fields/FS_Modulo__c.field-meta.xml
<CustomField>
    <fullName>FS_Modulo__c</fullName>
    <label>Módulo</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>FS_Producto__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GENERALES</fullName>
            </value>
            <value>
                <fullName>CLIENTES</fullName>
            </value>
            <value>
                <fullName>CAJA Y SERVICIOS</fullName>
            </value>
            <value>
                <fullName>CAPTACIONES VISTA</fullName>
            </value>
            <value>
                <fullName>CAPTACIONES A PLAZO</fullName>
            </value>
            <value>
                <fullName>COLOCACIONES</fullName>
            </value>
            <value>
                <fullName>ESTABLECIMIENTOS</fullName>
            </value>
            <value>
                <fullName>TARJETA DE CREDITO</fullName>
            </value>
            <value>
                <fullName>COMERCIO EXTERIOR</fullName>
            </value>
            <value>
                <fullName>MESA DE DINERO</fullName>
            </value>
            <value>
                <fullName>SERVICIOS</fullName>
            </value>
            <value>
                <fullName>TARJETA DE DEBITO</fullName>
            </value>
            <value>
                <fullName>INF. MANAGEMEN SYST. (IMS)</fullName>
            </value>
            <value>
                <fullName>CHECK CLEARING (ECCO)</fullName>
            </value>
            <value>
                <fullName>PROCESO DE DOCUMENTO (DIPS)</fullName>
            </value>
            <value>
                <fullName>CONTABILIDAD</fullName>
            </value>
            <value>
                <fullName>REPORTES DEL SISTEMA</fullName>
            </value>
            <value>
                <fullName>GARANTIAS</fullName>
            </value>
            <value>
                <fullName>SEGURIDAD INTERNA</fullName>
            </value>
            <value>
                <fullName>Business Application Products</fullName>
            </value>
            <value>
                <fullName>Business Application Generator</fullName>
            </value>
            <value>
                <fullName>Business Support Aplication</fullName>
            </value>
            <value>
                <fullName>Integration Service FSY</fullName>
            </value>
            <value>
                <fullName>Business Aplication</fullName>
            </value>
            <value>
                <fullName>Homebanking</fullName>
            </value>
            <value>
                <fullName>OLB-FT</fullName>
            </value>
            <value>
                <fullName>Móvil</fullName>
            </value>
            <value>
                <fullName>Kiosko</fullName>
            </value>
            <value>
                <fullName>Multichanel Management</fullName>
            </value>
            <value>
                <fullName>Motor Transaccional</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_ProductoAdquirido__c/fields/FS_Producto__c.field-meta.xml
<CustomField>
    <fullName>FS_Producto__c</fullName>
    <label>Producto</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FISA System</fullName>
            </value>
            <value>
                <fullName>FISA - Business Platform</fullName>
            </value>
            <value>
                <fullName>FISA Credit Card</fullName>
            </value>
            <value>
                <fullName>FISA FISS</fullName>
            </value>
            <value>
                <fullName>OMNIA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_ProductoAdquirido__c/fields/FS_SubModulo__c.field-meta.xml
<CustomField>
    <fullName>FS_SubModulo__c</fullName>
    <label>Sub Módulo</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>FS_Modulo__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Clientes (Módulo 2)</fullName>
            </value>
            <value>
                <fullName>Parametros Generales (Módulo 1)</fullName>
            </value>
            <value>
                <fullName>Seguridades (Modulo 90)</fullName>
            </value>
            <value>
                <fullName>Cuentas de Ahorro</fullName>
            </value>
            <value>
                <fullName>Cuentas Corrientes</fullName>
            </value>
            <value>
                <fullName>Cuentas de Acumulación</fullName>
            </value>
            <value>
                <fullName>Cuentas Nostro</fullName>
            </value>
            <value>
                <fullName>Cuentas Líneas de Crédito</fullName>
            </value>
            <value>
                <fullName>Depositos a Plazo Fijo</fullName>
            </value>
            <value>
                <fullName>Créditos de Consumo/Comerciales/Personales</fullName>
            </value>
            <value>
                <fullName>Crédito Automotriz</fullName>
            </value>
            <value>
                <fullName>Líneas de Crédito</fullName>
            </value>
            <value>
                <fullName>Crédito Hipotecario</fullName>
            </value>
            <value>
                <fullName>Crédito Hipotecario con Letras</fullName>
            </value>
            <value>
                <fullName>Cartas de crédito</fullName>
            </value>
            <value>
                <fullName>Cobranzas</fullName>
            </value>
            <value>
                <fullName>Avales</fullName>
            </value>
            <value>
                <fullName>Boletas de garantía</fullName>
            </value>
            <value>
                <fullName>Títulos y valores</fullName>
            </value>
            <value>
                <fullName>Cupones</fullName>
            </value>
            <value>
                <fullName>Tarjetas Nominadas</fullName>
            </value>
            <value>
                <fullName>Tarjetas Innominadas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DataFactory.cls
public class DataFactory {
    
    public static Account insertAccount(){
        Account acc = new Account();
        acc.Name = 'Account Test';
        insert acc;
        return acc;
    }
    
    public static Contact insertContact(Account acc){
        Contact contc = new Contact();
        contc.FirstName = 'FistName Test';
        contc.LastName = 'LastName Test';
        contc.AccountId = acc.Id;
        contc.Email = 'test@test.com';
        insert contc;
        return contc;
    }
    
    public static FS_ProductoAdquirido__c insertProduct(Account acc, String prod, String mod, String subM){
        FS_ProductoAdquirido__c p = new FS_ProductoAdquirido__c();
        p.FS_Cuenta__c = acc.Id;
        p.FS_Producto__c = prod;
        p.FS_Modulo__c = mod;
        p.FS_SubModulo__c = subM;
        insert p;
        return p;
    }
    
    public static Case insertCase(Account acc, Contact cont, FS_ProductoAdquirido__c p, String tipoRegistro){
        Case caso = new Case();
        caso.AccountId = acc.Id;
        caso.ContactId = cont.Id;
        caso.FS_Producto__c = p.FS_Producto__c;
        caso.FS_Modulo__c = p.FS_Modulo__c;
        caso.FS_SubModulo__c = p.FS_SubModulo__c;
        caso.FS_DescripcionCliente__c = '<p>Test</p>';
        caso.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get(tipoRegistro).getRecordTypeId();
        insert caso;
        return caso;
    }
        

}