force-app/main/default/objects/Case/fields/FS_Producto__c.field-meta.xml
<CustomField>
    <fullName>FS_Producto__c</fullName>
    <label>Producto</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FISA System</fullName>
            </value>
            <value>
                <fullName>FISA - Business Platform</fullName>
            </value>
            <value>
                <fullName>FISA Credit Card</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/FS_SubEstado__c.field-meta.xml
<CustomField>
    <fullName>FS_SubEstado__c</fullName>
    <label>Sub Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Apertura de caso</fullName>
                <default>true</default>
                <label>Apertura de caso</label>
            </value>
            <value>
                <fullName>Entrega 1a respuesta</fullName>
            </value>
            <value>
                <fullName>Información validada</fullName>
            </value>
            <value>
                <fullName>Análisis N1</fullName>
            </value>
            <value>
                <fullName>Desarrollo Incidente Definitivo</fullName>
            </value>
            <value>
                <fullName>Revisión Documentación N2</fullName>
            </value>
            <value>
                <fullName>Desarrollo Incidente Puntual</fullName>
            </value>
            <value>
                <fullName>Aprobación Solución IP-N2</fullName>
            </value>
            <value>
                <fullName>Aprobación de Solución IP-Release</fullName>
            </value>
            <value>
                <fullName>Costo Aceptado</fullName>
            </value>
            <value>
                <fullName>Costo Rechazado</fullName>
            </value>
            <value>
                <fullName>Análisis Falla Operativa</fullName>
            </value>
            <value>
                <fullName>Escalado a N2</fullName>
            </value>
            <value>
                <fullName>Análisis N2</fullName>
            </value>
            <value>
                <fullName>Envío de respuesta</fullName>
            </value>
            <value>
                <fullName>Respuesta aceptada</fullName>
            </value>
            <value>
                <fullName>Respuesta rechazada</fullName>
            </value>
            <value>
                <fullName>En reproceso por rechazo</fullName>
            </value>
            <value>
                <fullName>En Espera de Respuesta del Cliente</fullName>
            </value>
            <value>
                <fullName>Elaboración Diseño Técnico</fullName>
            </value>
            <value>
                <fullName>Aprobación Diseño Técnico</fullName>
            </value>
            <value>
                <fullName>Validación-Entrega de Fuentes</fullName>
            </value>
            <value>
                <fullName>Elaboración Solución Definitiva</fullName>
            </value>
            <value>
                <fullName>Aprobación Solución Definitiva N2</fullName>
            </value>
            <value>
                <fullName>Aprobación Solución Definitiva Releases</fullName>
            </value>
            <value>
                <fullName>Escalado a QA</fullName>
            </value>
            <value>
                <fullName>Elaboración Plan de Pruebas</fullName>
            </value>
            <value>
                <fullName>Aprobación Plan de Pruebas</fullName>
            </value>
            <value>
                <fullName>Instalación Parche Releases</fullName>
            </value>
            <value>
                <fullName>Aprobación Instalación Parche - Releases</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TrabajoAgenteHelper.cls
public class TrabajoAgenteHelper {

    public static void verificacionCaso(List<AgentWork> newAgentWork){
        List<String> recordIds = new List<String>();
        List<String> listUserId = new  List<String>();
        List<String> listUser = new  List<String>();
        List<Case> listCasosActualizar = new List<Case>();
        
        for(AgentWork item: newAgentWork){
            recordIds.add(item.WorkItemId);
            listUserId.add(item.UserId);
        }
        String query = 'Select ';
        Map<String, Schema.SObjectField> fieldMap = Schema.getGlobalDescribe().get('Case').getDescribe().fields.getMap();
        for(Schema.SObjectField sfield : fieldMap.Values()){
            schema.describefieldresult dfield = sfield.getDescribe();
            query += dfield.getname() + ',';
        }
        query = query.substring(0, query.length() - 1) + ' from Case Where Id in :recordIds';
        List<Case> listCasos = DataBase.query(query);
        for(User item :[Select Id from User Where Id in :listUserId]){
            listUser.add(item.Id);
        }
        List<String> colasAtencion = new List<String>();
        List<String> colasAtencionN2 = new List<String>();
        for(Group item: [Select Id,Developername from Group Where DeveloperName In ('FS_AtencionN1Core', 'FS_AtencionN1Omnia','FS_AtencionN2Core', 'FS_AtencionN2Omnia') and Type = 'Queue']){
            if(item.DeveloperName == 'FS_AtencionN1Core' || item.DeveloperName == 'FS_AtencionN1Omnia'){
                colasAtencion.add(item.Id);
            }else if(item.DeveloperName == 'FS_AtencionN2Core' || item.DeveloperName == 'FS_AtencionN2Omnia'){
                colasAtencionN2.add(item.Id);
            }
        }
        for(Case item: listCasos){
            Boolean esCore = item.FS_Producto__c == 'FISA System' || item.FS_Producto__c == 'FISA Credit Card' ;
            for(AgentWork aw: newAgentWork){
                if(item.Id == aw.WorkItemId && listUser.contains(aw.UserId) && colasAtencion.contains(aw.OriginalQueueId) &&
                  item.FS_SubEstado__c == 'Apertura de caso'){
                      item.FS_SubEstado__c = 'Entrega 1a respuesta';
                      CaseTriggerHelper.envioCorreo(item, 'FS_AsignacionCaso', true);
                      listCasosActualizar.add(item);
                  }else if(item.Id == aw.WorkItemId && listUser.contains(aw.UserId) && colasAtencionN2.contains(aw.OriginalQueueId) &&
                           item.FS_SubEstado__c == 'Escalado a N2' && item.FS_NombreTipoRegistro__c == 'Incidente'){
                               item.FS_SubEstado__c = 'Revisión Documentación N2';
                               listCasosActualizar.add(item);
                  }
            }
        }
        update listCasosActualizar;
    }
}