force-app/main/default/objects/Case/fields/FS_SubEstado__c.field-meta.xml
<CustomField>
    <fullName>FS_SubEstado__c</fullName>
    <label>Sub Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Apertura de caso</fullName>
                <default>true</default>
                <label>Apertura de caso</label>
            </value>
            <value>
                <fullName>Entrega 1a respuesta</fullName>
            </value>
            <value>
                <fullName>Información validada</fullName>
            </value>
            <value>
                <fullName>Análisis N1</fullName>
            </value>
            <value>
                <fullName>Desarrollo Incidente Definitivo</fullName>
            </value>
            <value>
                <fullName>Revisión Documentación N2</fullName>
            </value>
            <value>
                <fullName>Desarrollo Incidente Puntual</fullName>
            </value>
            <value>
                <fullName>Aprobación Solución IP-N2</fullName>
            </value>
            <value>
                <fullName>Aprobación de Solución IP-Release</fullName>
            </value>
            <value>
                <fullName>Costo Aceptado</fullName>
            </value>
            <value>
                <fullName>Costo Rechazado</fullName>
            </value>
            <value>
                <fullName>Análisis Falla Operativa</fullName>
            </value>
            <value>
                <fullName>Escalado a N2</fullName>
            </value>
            <value>
                <fullName>Análisis N2</fullName>
            </value>
            <value>
                <fullName>Envío de respuesta</fullName>
            </value>
            <value>
                <fullName>Respuesta aceptada</fullName>
            </value>
            <value>
                <fullName>Respuesta rechazada</fullName>
            </value>
            <value>
                <fullName>En reproceso por rechazo</fullName>
            </value>
            <value>
                <fullName>En Espera de Respuesta del Cliente</fullName>
            </value>
            <value>
                <fullName>Elaboración Diseño Técnico</fullName>
            </value>
            <value>
                <fullName>Aprobación Diseño Técnico</fullName>
            </value>
            <value>
                <fullName>Validación-Entrega de Fuentes</fullName>
            </value>
            <value>
                <fullName>Elaboración Solución Definitiva</fullName>
            </value>
            <value>
                <fullName>Aprobación Solución Definitiva N2</fullName>
            </value>
            <value>
                <fullName>Aprobación Solución Definitiva Releases</fullName>
            </value>
            <value>
                <fullName>Escalado a QA</fullName>
            </value>
            <value>
                <fullName>Elaboración Plan de Pruebas</fullName>
            </value>
            <value>
                <fullName>Aprobación Plan de Pruebas</fullName>
            </value>
            <value>
                <fullName>Instalación Parche Releases</fullName>
            </value>
            <value>
                <fullName>Aprobación Instalación Parche - Releases</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/FS_Consulta.recordType-meta.xml
<RecordType>
    <fullName>FS_Consulta</fullName>
    <active>true</active>
    <businessProcess>FS_Casos</businessProcess>
    <label>Consulta</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/FS_Incidente.recordType-meta.xml
<RecordType>
    <fullName>FS_Incidente</fullName>
    <active>true</active>
    <businessProcess>FS_CasoIncidente</businessProcess>
    <label>Incidente</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/FS_Solicitud.recordType-meta.xml
<RecordType>
    <fullName>FS_Solicitud</fullName>
    <active>true</active>
    <businessProcess>FS_CasoSolicitud</businessProcess>
    <label>Solicitud</label>
</RecordType>

force-app/main/default/objects/FS_ProductoAdquirido__c/FS_ProductoAdquirido__c.object-meta.xml
<CustomObject>
    <label>Producto Adquirido</label>
    <nameField>
        <label>Nombre de Categoría</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Productos Adquiridos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/FeedCommentTriggerHelper_Test.cls
@isTest
public class FeedCommentTriggerHelper_Test {
    
    @TestSetup
    static void setup(){
        Account acc = DataFactory.insertAccount();
        Contact cont = DataFactory.insertContact(acc);
        DataFactory.insertUserCommunity(cont);
        FS_ProductoAdquirido__c p = DataFactory.insertProduct(acc, 'FISA System', 'Núcleo del Sistema', '');
        DataFactory.insertCase(acc, cont, p, 'FS_Consulta');
        DataFactory.insertCase(acc, cont, p, 'FS_Solicitud');
        DataFactory.insertCase(acc, cont, p, 'FS_Incidente');
        DataFactory.insertProduct(acc, 'FISA System', 'Núcleo del Sistema', '');
    }
    
    @isTest
    static void FeedComment() {
        User u = [Select Id from User Where Profile.Name = 'Customer Community User' limit 1];
        Case caso =  [Select Id, RecordType.DeveloperName, FS_SubEstadoQueSePideInformacion__c, FS_SubEstado__c from Case Where RecordTypeId = :CaseTriggerHelper.CONSULTA_TIPO_REGISTRO];
        caso.FS_SubEstado__c = 'Apertura de caso';
        caso.FS_SubEstadoQueSePideInformacion__c = caso.FS_SubEstado__c;
        update caso;
        Test.startTest();
        caso.FS_InformacionCompleta__c = 'No';
        update caso;
        System.runAs(u){
            FeedItem fi = new FeedItem(ParentId = caso.Id, Body = 'Test', Visibility = 'AllUsers');
            insert fi;
            FeedComment df = new FeedComment (FeedItemId = fi.Id, CommentBody = fi.Body);
            insert df;
            Database.delete(df, false);
            Database.delete(fi, false);
            
        }
        Test.stopTest();
        
    }

}