force-app/main/default/objects/FS_ProductoAdquirido__c/FS_ProductoAdquirido__c.object-meta.xml
<CustomObject>
    <label>Producto Adquirido</label>
    <nameField>
        <label>Nombre de Categoría</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Productos Adquiridos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_ProductoAdquirido__c/fields/FS_Modulo__c.field-meta.xml
<CustomField>
    <fullName>FS_Modulo__c</fullName>
    <label>Módulo</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>FS_Producto__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GENERALES</fullName>
            </value>
            <value>
                <fullName>CLIENTES</fullName>
            </value>
            <value>
                <fullName>CAJA Y SERVICIOS</fullName>
            </value>
            <value>
                <fullName>CAPTACIONES VISTA</fullName>
            </value>
            <value>
                <fullName>CAPTACIONES A PLAZO</fullName>
            </value>
            <value>
                <fullName>COLOCACIONES</fullName>
            </value>
            <value>
                <fullName>ESTABLECIMIENTOS</fullName>
            </value>
            <value>
                <fullName>TARJETA DE CREDITO</fullName>
            </value>
            <value>
                <fullName>COMERCIO EXTERIOR</fullName>
            </value>
            <value>
                <fullName>MESA DE DINERO</fullName>
            </value>
            <value>
                <fullName>SERVICIOS</fullName>
            </value>
            <value>
                <fullName>TARJETA DE DEBITO</fullName>
            </value>
            <value>
                <fullName>INF. MANAGEMEN SYST. (IMS)</fullName>
            </value>
            <value>
                <fullName>CHECK CLEARING (ECCO)</fullName>
            </value>
            <value>
                <fullName>PROCESO DE DOCUMENTO (DIPS)</fullName>
            </value>
            <value>
                <fullName>CONTABILIDAD</fullName>
            </value>
            <value>
                <fullName>REPORTES DEL SISTEMA</fullName>
            </value>
            <value>
                <fullName>GARANTIAS</fullName>
            </value>
            <value>
                <fullName>SEGURIDAD INTERNA</fullName>
            </value>
            <value>
                <fullName>Business Application Products</fullName>
            </value>
            <value>
                <fullName>Business Application Generator</fullName>
            </value>
            <value>
                <fullName>Business Support Aplication</fullName>
            </value>
            <value>
                <fullName>Integration Service FSY</fullName>
            </value>
            <value>
                <fullName>Business Aplication</fullName>
            </value>
            <value>
                <fullName>Homebanking</fullName>
            </value>
            <value>
                <fullName>OLB-FT</fullName>
            </value>
            <value>
                <fullName>Móvil</fullName>
            </value>
            <value>
                <fullName>Kiosko</fullName>
            </value>
            <value>
                <fullName>Multichanel Management</fullName>
            </value>
            <value>
                <fullName>Motor Transaccional</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_ProductoAdquirido__c/fields/FS_Producto__c.field-meta.xml
<CustomField>
    <fullName>FS_Producto__c</fullName>
    <label>Producto</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FISA System</fullName>
            </value>
            <value>
                <fullName>FISA - Business Platform</fullName>
            </value>
            <value>
                <fullName>FISA Credit Card</fullName>
            </value>
            <value>
                <fullName>FISA FISS</fullName>
            </value>
            <value>
                <fullName>OMNIA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_ProductoAdquirido__c/fields/FS_SubModulo__c.field-meta.xml
<CustomField>
    <fullName>FS_SubModulo__c</fullName>
    <label>Sub Módulo</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>FS_Modulo__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Clientes (Módulo 2)</fullName>
            </value>
            <value>
                <fullName>Parametros Generales (Módulo 1)</fullName>
            </value>
            <value>
                <fullName>Seguridades (Modulo 90)</fullName>
            </value>
            <value>
                <fullName>Cuentas de Ahorro</fullName>
            </value>
            <value>
                <fullName>Cuentas Corrientes</fullName>
            </value>
            <value>
                <fullName>Cuentas de Acumulación</fullName>
            </value>
            <value>
                <fullName>Cuentas Nostro</fullName>
            </value>
            <value>
                <fullName>Cuentas Líneas de Crédito</fullName>
            </value>
            <value>
                <fullName>Depositos a Plazo Fijo</fullName>
            </value>
            <value>
                <fullName>Créditos de Consumo/Comerciales/Personales</fullName>
            </value>
            <value>
                <fullName>Crédito Automotriz</fullName>
            </value>
            <value>
                <fullName>Líneas de Crédito</fullName>
            </value>
            <value>
                <fullName>Crédito Hipotecario</fullName>
            </value>
            <value>
                <fullName>Crédito Hipotecario con Letras</fullName>
            </value>
            <value>
                <fullName>Cartas de crédito</fullName>
            </value>
            <value>
                <fullName>Cobranzas</fullName>
            </value>
            <value>
                <fullName>Avales</fullName>
            </value>
            <value>
                <fullName>Boletas de garantía</fullName>
            </value>
            <value>
                <fullName>Títulos y valores</fullName>
            </value>
            <value>
                <fullName>Cupones</fullName>
            </value>
            <value>
                <fullName>Tarjetas Nominadas</fullName>
            </value>
            <value>
                <fullName>Tarjetas Innominadas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ControladorBaseConocimientos.cls
public without sharing class ControladorBaseConocimientos {

    private static Integer NUMERO_MESES_KNOWLEDGE = 6;
     @AuraEnabled
    public static BaseConocimientoWrapper gatListaBase(){
        BaseConocimientoWrapper respuesta = new BaseConocimientoWrapper();
        ControladorCrearCaso.ContactoWrapper prod = ControladorCrearCaso.getProductosAdquiridos();
        respuesta.listProducto = ControladorCrearCaso.getProductosAdquiridos().listTodosProductos;
        respuesta.listBaseConocimiento = new List<BaseConocimiento>();
        user usuario = [Select ContactId, Contact.AccountId, CreatedDate from User  Where Id = :userInfo.getUserId()];
        for(FS_BaseConocimiento__c item: 
            [Select Name, FS_Contenido__c, FS_Producto__c, FS_Modulo__c, FS_SubModulo__c, FS_ProductoAdquirido__c 
             from FS_BaseConocimiento__c 
             where FS_Activo__c = true  and  
             (FS_ProductoAdquirido__r.FS_Cuenta__c =: usuario.Contact.AccountId or FS_ProductoAdquirido__c = null) Order by FS_ProductoAdquirido__c, CreatedDate desc]){
                 BaseConocimiento base = new BaseConocimiento();
                 base.productoVacio = String.isBlank(item.FS_ProductoAdquirido__c);
                 if(!base.productoVacio || usuario.CreatedDate >= system.now().addMonths(-NUMERO_MESES_KNOWLEDGE) ){
                     item.FS_Contenido__c = String.isNotBlank(item.FS_Contenido__c) ? item.FS_Contenido__c : '';
                     base.contenido = item.FS_Contenido__c;
                     base.contenidoPlano = item.FS_Contenido__c.stripHtmlTags();
                     base.nombre = item.Name;
                     base.producto = item.FS_Producto__c;
                     base.modulo = item.FS_Modulo__c;
                     base.subModulo = item.FS_SubModulo__c;
                     base.id = item.Id;
                     respuesta.listBaseConocimiento.add(base);
                 }
             }
        return respuesta;
    }
    
    public class BaseConocimientoWrapper{
        @AuraEnabled public List<BaseConocimiento> listBaseConocimiento{get;set;}
        @AuraEnabled public List<ControladorCrearCaso.Producto> listProducto{get;set;}
    }
    
    public class BaseConocimiento{
        @AuraEnabled public String contenido {get;set;}
        @AuraEnabled public String contenidoPlano {get;set;}
        @AuraEnabled public String nombre {get;set;}
        @AuraEnabled public String producto {get;set;}
        @AuraEnabled public String modulo {get;set;}
        @AuraEnabled public String subModulo {get;set;}
        @AuraEnabled public Boolean productoVacio {get;set;}
        @AuraEnabled public String id {get;set;}
    }
}